### PR TITLE
--collapse-double-clusters command line option

### LINKED ISSUE #29: Command line option for `collapseDoubleClusters`
Hi,

First, thanks a lot for this great tool! It helps a lot to visualize a solution architecture based on the actual implementation and keep it up to date :)

I my projects, I sometimes create custom constructs that wrap existing L2 constructs. The reason I am doing this is to express the function of the logical unit ([example](https://github.com/alexpulver/usermanagement-backend/blob/afdcec066d2619054d377ce905ec905fb946fd76/toolchain.py#L135-L158)). `cdk-dia` collapses these constructs automatically:
https://github.com/pistazie/cdk-dia/blob/dcd3237ee89deeccc8f29208e150ca0c959d1b30/src/diagram/aws/aws-diagram-generator.ts#L45

Showing the aforementioned logical units in the diagram helps with readability (see examples of before/after below). It would be helpful to have a separate option to toggle this behavior. If that sounds like a good idea, what do you think about renaming the existing `--collapse` option to `--collapse-constructs` and introducing a new `--collapse-clusters` option?

Before | After
-- | --
diagram | diagram-clusters

### PR DESCRIPTION
**Pull request by alexpulver**
Expose a command line option for the following behavior:
https://github.com/pistazie/cdk-dia/blob/dcd3237ee89deeccc8f29208e150ca0c959d1b30/src/diagram/aws/aws-diagram-generator.ts#L45

Closes #29

### CODE REVIEW

**Comment by pistazie** [comment]
@alexpulver the PR didn't pass but CI seems to have been broken on master before. will fix that soon.

**Comment by pistazie** [comment]
@alexpulver can you please rebase on `main`?
the tests were broken before.

**Comment by alexpulver** [comment]
@pistazie will do, thanks!

**Review by pistazie — APPROVED** [review]

**Comment by pistazie** [comment]
@alexpulver published as `0.8.0`. thanks!

**Comment by alexpulver** [comment]
@pistazie thank you for the review and quick release! Time to update diagrams 😄

**Pull request merged**
